# OddRoyal Application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddroyal-deployment
  namespace: oddroyal
  labels:
    app: oddroyal
    component: application
spec:
  replicas: 3  # Multiple replicas for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: oddroyal
  template:
    metadata:
      labels:
        app: oddroyal
        component: application
    spec:
      serviceAccountName: oddroyal-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: oddroyal
        image: oddroyal/admin-panel:latest  # Replace with your actual image
        ports:
        - containerPort: 3000
          name: http
        env:
        # Configuration from ConfigMap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: PORT
        - name: ADMIN_BASE_PATH
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: ADMIN_BASE_PATH
        - name: ADMIN_2FA_ENFORCED
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: ADMIN_2FA_ENFORCED
        - name: RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: RATE_LIMIT_WINDOW_MS
        - name: RATE_LIMIT_MAX_REQUESTS
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: RATE_LIMIT_MAX_REQUESTS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: LOG_LEVEL
        - name: DEMO_MODE
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: DEMO_MODE
        - name: MAINTENANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: MAINTENANCE_MODE
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: PGHOST
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: PGPORT
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: PGDATABASE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: oddroyal-config
              key: REDIS_PORT
        
        # Secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: DATABASE_URL
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: REDIS_PASSWORD
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: JWT_SECRET
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: ADMIN_JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: SESSION_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: ENCRYPTION_KEY
        - name: SPORTMONKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: SPORTMONKS_API_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: STRIPE_SECRET_KEY
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: SENTRY_DSN
        
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-uploads
          mountPath: /app/uploads
        - name: temp-storage
          mountPath: /tmp
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-service -p 5432 -U oddroyal; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: oddroyal-secrets
              key: POSTGRES_USER
      
      - name: wait-for-redis
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          until redis-cli -h redis-service -p 6379 ping; do
            echo "Waiting for Redis to be ready..."
            sleep 2
          done
          echo "Redis is ready!"
      
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: oddroyal-logs-pvc
      - name: app-uploads
        persistentVolumeClaim:
          claimName: oddroyal-uploads-pvc
      - name: temp-storage
        emptyDir: {}
      
      # Pod disruption budget for high availability
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: oddroyal

---
# OddRoyal Service
apiVersion: v1
kind: Service
metadata:
  name: oddroyal-service
  namespace: oddroyal
  labels:
    app: oddroyal
    component: application
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: oddroyal

---
# Persistent Volume Claims for application data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oddroyal-logs-pvc
  namespace: oddroyal
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods need access
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oddroyal-uploads-pvc
  namespace: oddroyal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Service Account for OddRoyal
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oddroyal-service-account
  namespace: oddroyal
  labels:
    app: oddroyal

---
# Pod Disruption Budget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oddroyal-pdb
  namespace: oddroyal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: oddroyal